import mongoose from 'mongoose';

const ticketReplySchema = new mongoose.Schema({
  message: {
    type: String,
    required: true
  },
  repliedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: true
  },
  repliedByName: {
    type: String,
    required: true
  },
  repliedByEmail: {
    type: String,
    required: true
  },
  isAdmin: {
    type: Boolean,
    default: false
  },
  createdAt: {
    type: Date,
    default: Date.now
  }
});

const ticketSchema = new mongoose.Schema({
  // Ticket Information
  ticketNumber: {
    type: String,
    required: false // Auto-generated by pre-save hook
  },
  type: {
    type: String,
    enum: ['issue', 'support'],
    required: true
  },
  category: {
    type: String,
    required: true
  },
  
  // Submitter Information
  submittedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User',
    required: false // Support messages might be from non-users
  },
  submitterName: {
    type: String,
    required: true
  },
  submitterEmail: {
    type: String,
    required: true
  },
  
  // Ticket Content
  subject: {
    type: String,
    required: true
  },
  message: {
    type: String,
    required: true
  },
  
  // Status & Priority
  status: {
    type: String,
    enum: ['open', 'in-progress', 'resolved', 'closed'],
    default: 'open'
  },
  priority: {
    type: String,
    enum: ['low', 'medium', 'high', 'urgent'],
    default: 'medium'
  },
  
  // Assignment
  assignedTo: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  assignedToName: String,
  
  // Replies/Conversation
  replies: [ticketReplySchema],
  
  // Timestamps
  lastReplyAt: Date,
  resolvedAt: Date,
  closedAt: Date,
  
  // Metadata
  tags: [String],
  attachments: [{
    filename: String,
    url: String,
    uploadedAt: Date
  }]
}, {
  timestamps: true
});

// Generate ticket number
ticketSchema.pre('save', async function(next) {
  if (!this.ticketNumber) {
    const count = await this.constructor.countDocuments();
    const prefix = this.type === 'issue' ? 'ISS' : 'SUP';
    this.ticketNumber = `${prefix}-${String(count + 1).padStart(6, '0')}`;
  }
  next();
});

// Update lastReplyAt when a reply is added
ticketSchema.pre('save', function(next) {
  if (this.isModified('replies') && this.replies.length > 0) {
    this.lastReplyAt = this.replies[this.replies.length - 1].createdAt;
  }
  next();
});

// Indexes for efficient querying
ticketSchema.index({ ticketNumber: 1 });
ticketSchema.index({ status: 1, createdAt: -1 });
ticketSchema.index({ submittedBy: 1, createdAt: -1 });
ticketSchema.index({ assignedTo: 1, status: 1 });
ticketSchema.index({ type: 1, status: 1 });

const Ticket = mongoose.model('Ticket', ticketSchema);

export default Ticket;
